MAIN_SECTION = 'Main'
STATION_SETTINGS_KEY = 'Station Settings'
OSPI_VERSION_KEY = 'ospi version'
STATION_SECTION_KEY = 'Station %d'
TZ_KEY = 'time zone'
SYS_VERSION_KEY = 'system version'
DATE_FORMAT_KEY = 'date format'
TIME_FORMAT_KEY = 'time format'
LOCATION_KEY = 'location'
RAIN_SENSOR_KEY = 'rain sensor'
INVERT_RAIN_SENSOR_KEY = 'invert rain sensor'
STATIONS_AVAIL_KEY = 'stations available'
STATION_NAME_KEY = 'name'
WIRED_KEY = 'wired'
IGNORE_RAIN_KEY = 'ignore rain sensor'
NEED_MASTER_KEY = 'need master'
STATION_LIST_KEY = 'station list'
PROGRAM_ID_KEY = "pid"
TIME_OF_DAY_KEY = "time_of_day"
INTERVAL_KEY = "interval"
INTERVAL_TYPE_KEY = "type"
RUN_DAYS_KEY = "run_days"
IN_PROGRAM_KEY = "in_program"
TOTAL_RUN_TIME_KEY = "total_run_time"
STATION_DURATION_KEY = "station_duration"
STATION_ID_KEY = "stid"
DURATION_KEY = "duration"
IN_STATION_KEY = "in_station"

EVEN_INTERVAL_TYPE = "even"
ODD_INTERVAL_TYPE = "odd"
DOW_INTERVAL_TYPE = "day_of_week"